# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Berechnung von SWT und FS-Sch\xe4digungsparameter', kernelModule='startupGUI', kernelFunction='startupGUI', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgGroupBox(name='GroupBox_3', p='DialogBox', text='Fatemi-Socie', layout='0')
RsgIcon(p='GroupBox_3', fileName=r'FS.PNG')
RsgGroupBox(name='GroupBox_2', p='DialogBox', text='Smith-Watson-Topper', layout='0')
RsgIcon(p='GroupBox_2', fileName=r'SWT.PNG')
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='Materialparameter')
RsgGroupBox(name='GroupBox_1', p='TabItem_1', text='Materialparameter', layout='0')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=15, labelText='E-Modul [GPa]', keyword='E', default='20450')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=15, labelText='Streckgrenze [MPa]', keyword='S_yield', default='450')
RsgSlider(p='GroupBox_1', text='k', minLabelText='0', maxLabelText='1', valueType=FLOAT, minValue=0, maxValue=1, decimalPlaces=2, showValue=True, width=200, keyword='k', default=0.5)
RsgSeparator(p='GroupBox_1')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=25, labelText='Odb-Name', keyword='odb_name', default='oe_8_Elements')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=25, labelText='Part-Name', keyword='part_name', default='PolyElement')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Step-Name:', keyword='StepName', default='Step-1')
RsgTextField(p='GroupBox_1', fieldType='String', ncols=12, labelText='Set-Name', keyword='SetName', default='None')
RsgSeparator(p='GroupBox_1')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='Start-Step-Time', keyword='t_begin', default='0')
RsgTextField(p='GroupBox_1', fieldType='Float', ncols=12, labelText='End-Step-Time', keyword='t_end', default='10')
RsgComboBox(name='ComboBox_1', p='GroupBox_1', text='Methode', keyword='frame_flag', default='All', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_1', text='All')
RsgListItem(p='ComboBox_1', text='Intervall')
RsgListItem(p='ComboBox_1', text='Fixed')
RsgLabel(p='GroupBox_1', text='Viel Spa\xdf', useBoldFont=True)
RsgTabItem(name='TabItem_2', p='TabBook_1', text='Parameter f\xfcr Lebensdauerberechnung')
RsgSlider(p='TabItem_2', text='F\xfcr wie viele Elemente soll die Lebensdauer berechnet werden?', minLabelText='Worst Case Element', maxLabelText='Alle Elemente', valueType=FLOAT, minValue=0, maxValue=1, decimalPlaces=2, showValue=True, width=440, keyword='portion', default=0.5)
RsgSeparator(p='TabItem_2')
RsgTextField(p='TabItem_2', fieldType='Float', ncols=12, labelText='b:', keyword='b', default='-0.113')
RsgTextField(p='TabItem_2', fieldType='Float', ncols=12, labelText='c:', keyword='c', default='-610')
RsgTextField(p='TabItem_2', fieldType='Float', ncols=12, labelText='sigma_F', keyword='sigma_F', default='1311')
RsgTextField(p='TabItem_2', fieldType='Float', ncols=12, labelText='epsilion_F:', keyword='epsilion_F', default='0.8755')
dialogBox.show()